// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvw2zMcOjCWY-1h81x9dwRG_tBPLV1yA',
    appId: '1:386315781988:web:901a0be9672b65c6335c71',
    messagingSenderId: '386315781988',
    projectId: 'converter-flutter',
    authDomain: 'converter-flutter.firebaseapp.com',
    storageBucket: 'converter-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-RUP-1RrSLGULrQWKloyJ1H-ltE3CQlU',
    appId: '1:386315781988:android:5b5ec29dc20c5f3e335c71',
    messagingSenderId: '386315781988',
    projectId: 'converter-flutter',
    storageBucket: 'converter-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFgyvw8y-0F5z0WuQNW9KyMjs_49_ZJ30',
    appId: '1:386315781988:ios:a1887e9a2af17d2e335c71',
    messagingSenderId: '386315781988',
    projectId: 'converter-flutter',
    storageBucket: 'converter-flutter.firebasestorage.app',
    iosBundleId: 'com.dime.converterFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFgyvw8y-0F5z0WuQNW9KyMjs_49_ZJ30',
    appId: '1:386315781988:ios:a1887e9a2af17d2e335c71',
    messagingSenderId: '386315781988',
    projectId: 'converter-flutter',
    storageBucket: 'converter-flutter.firebasestorage.app',
    iosBundleId: 'com.dime.converterFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLvw2zMcOjCWY-1h81x9dwRG_tBPLV1yA',
    appId: '1:386315781988:web:202f9fc1b603cf98335c71',
    messagingSenderId: '386315781988',
    projectId: 'converter-flutter',
    authDomain: 'converter-flutter.firebaseapp.com',
    storageBucket: 'converter-flutter.firebasestorage.app',
  );
}
